### PR TITLE
Fix channel chat page's chat list box not growing in width.

### LINKED ISSUE #5: Chat channel page layout not growing
## Simple Description
Main chat list box does not grow in width as intended.

## Expected Behavior
Screenshot 2023-12-25 at 6 25 56 PM

## Actual Behavior
Screenshot 2023-12-25 at 6 20 56 PM

## Steps to Reproduce the Problem

1. Go to `Channels` page in dashboard
2. Click on a channel

### PR DESCRIPTION
**Pull request by yhware**
## ✍️ Describe your changes
- Fixed chat channel page layout css typo

## 🎟 ️Issue ticket number and link

closes #5 

## ✅ Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

File: src/components/channel/ChannelChatBox.tsx [hunk 1]
```diff
@@ -171,8 +171,7 @@ const ChannelChatBox = ({
   };
 
   return (
-    <Box flex="1'0 auto">
-      '{' '}
```
Comment (yhware) [inline src/components/channel/ChannelChatBox.tsx:175]: It was a simple typo

File: src/components/channel/ChannelInfoSideBar.tsx [hunk 2]
```diff
@@ -46,8 +46,8 @@ export const ChannelInfoSideBar = ({ onClose }: { onClose: () => void }) => {
   const [membersDrawerOpen, setMembersDrawerOpen] = useState(false);
 
   return (
-    <ChannelInfoRightSideBar flex="320'x">
-      ' {/*  channel info */}
```
Comment (yhware) [inline src/components/channel/ChannelInfoSideBar.tsx:50]: Also a typo
